---
apiVersion: v1
kind: Service
metadata:
  name: basic-laravel-service
spec:
  loadBalancerIP: 192.168.0.213
  type: LoadBalancer
  selector:
    app: basic-laravel
  ports:
    - name: http
      port: 8080
